/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:5
-- pg_open_meteo::hello_pg_open_meteo
CREATE  FUNCTION "hello_pg_open_meteo"() RETURNS TEXT /* &str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'hello_pg_open_meteo_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:10
-- pg_open_meteo::strictly_positive
CREATE  FUNCTION "strictly_positive"(
	"a" INT /* i32 */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'strictly_positive_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:15
-- pg_open_meteo::x_must_be_bigger_than_y
CREATE  FUNCTION "x_must_be_bigger_than_y"(
	"x" INT, /* i32 */
	"y" INT /* i32 */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'x_must_be_bigger_than_y_wrapper';
/* </end connected objects> */

